### ISSUE TITLE
Get Started button isn't working property -> redirects to {host}/index.html

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fable-compiler/fable-compiler.github.io#100]

**Comment by alfonsogarciacaro** [comment]
The issue here is that the doc page is now /documentation instead of /docs. Unfortunately this breaks all existing links, can we use /docs instead @MangelMaxime?

**Comment by alfonsogarciacaro** [comment]
Fixed by 0bbd0ec7249d741bfaefdbab300c75b34b23d7fe

If possible, please @MangelMaxime have a look at the commit to make sure I did things properly :)

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro Everything look fine to me :+1:
