### ISSUE TITLE
Configure a CI to check the validity of the links included in the resource.md file

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/fable-compiler.github.io#104]
Here is how it is done in the original Fable awesome repository:

https://github.com/kunjee17/awesome-fable/blob/master/.travis.yml

I think we just need to setup a workflow with ruby installed to install the `awesome_bot` and the command line.

**Comment by MangelMaxime** [comment]
It would nice if we could make it run on PR/master and perhaps have the publish CI wait for this workflow to succeeded before publishing a new version of the website.

If I remember correctly @cartermp you are the one who setup the current workflow.

Do you know, if it is possible to make a workflow wait for another workflow to complete before running?

**Comment by cartermp** [comment]
@MangelMaxime I believe if it's a step within the same workflow that precedes publish then it should work just fine.

**Comment by MangelMaxime** [comment]
You are right it should works.

In the end, I decide to create another workflow which will run against PR targeting `dev` branch. This should allows us to detect errors before merging it to master branch.
