### ISSUE TITLE
Website link to bulma-timepicker is broken (https://fable.io/resources.html)

### ISSUE THREAD

**Issue by reneederer** [fable-compiler/fable-compiler.github.io#126]
Hi,
on https://fable.io/resources.html the link for "bulma-timepicker"
incorrectly links to [https://github.com/rfrerebe/fable2-samples/tree/master/minimal](https://github.com/rfrerebe/fable2-samples/tree/master/minimal)

**Comment by MangelMaxime** [comment]
Hello @reneederer,

Thank you.

I removed the item because I don't know where it should be pointed to.
