### ISSUE TITLE
Getting started: the command to download the Fable template could be wrong

### ISSUE THREAD

**Issue by palutz** [fable-compiler/fable-compiler.github.io#13]
In the Getting started page (http://fable.io/docs/getting-started.html), the snippet for downloading the Fable template for dotnet core looks wrong (it doesn't work for Mac and Linux).
On the site the snippet is:
`dotnet new -i Fable.Template`
> Error: Package "Fable.Template" is not a valid package specification

while it should be:
`dotnet new -i "Fable.Template::*"`

**Comment by MangelMaxime** [comment]
This is because you are still using dotnet 1.0.x

On the getting started page we put dotnet 2.0 has a requirement because now Fable use it.

**Comment by palutz** [comment]
Good point. It looks like that machine wasn't updated. Thanks. I will close it.
