### ISSUE TITLE
Qt

### ISSUE THREAD

**Issue by ShalokShalom** [fable-compiler/fable-compiler.github.io#14]
[Qt](https://www.qt.io/) is an open source library collection. 

Javascript supports the whole set of it and QML is one of the diamonds in this toolset. 
It is possible to use JS and QML in order to develop native desktop and phone applications. 

Supported platforms are Android, iOS, macOS, Wayland, Windows, X.org and a bunch of others: 
All that with one and the same code. 

Those applications are inherently GPU accelerated, scale automatically to the used screen size and can delight our eyes by smooth animations. 

It's possible to code the logic with JS and then use the [WYSIWYG](http://doc.qt.io/qtcreator/creator-using-qt-quick-designer.html ) designer in Qt Creator to design the UI: 
So you dont even need to code for the UI. 

You call it by Qt Quick 2 JIT and you can compile it into C++ with the superb [Qt Quick Compiler.](http://doc.qt.io/QtQuickCompiler/)

You can do pretty much all the IO in Qt.

**Comment by MangelMaxime** [comment]
Hello @ShalokShalom I am not sure to understand your issue here ?

Is it a question somehow ?

**Comment by ShalokShalom** [comment]
Yes, since Qt is underrepresented on your homepage.

This is a use case, which deserves much attention if you ask me. :)

**Comment by MangelMaxime** [comment]
Sure, but we don't have any working sample on top of it. So for now, it's kind of hard to make propaganda on it :)

**Comment by ShalokShalom** [comment]
Yeah, I see. 

I like to create something. The thing is, that my experience in programming is mostly theoretically since I started just some weeks ago to get interested into it. 

So, currently is my person less capable to create such a stuff, since the correct implementation is currently a little bit vague, to be honest. 

JS can get written inline .qml documents and I can also import .js files into them. 
The thing is, that this counts for qml interfaces, while the other qt libraries get called in javascript directly.

So, I like to suggest that some of you consider to contribute a little page or so about the possibilities, so as I do it here. Some others can start then to code some real world examples.
