### ISSUE TITLE
Fable Server

### ISSUE THREAD

**Issue by ShalokShalom** [fable-compiler/fable-compiler.github.io#17]
This documentation seems to be missing: https://github.com/fable-compiler/Fable/blob/master/src/dotnet/dotnet-fable/Server.fs

**Comment by alfonsogarciacaro** [comment]
What do you mean? Documentation about the Fable server/daemon? Theres a quick mention [in this section](http://fable.io/docs/getting-started.html#a-bit-longer-explanation) but I didn't want to write too much to avoid confusion as most of the times the daemon remains transparent to the user.

**Comment by ShalokShalom** [comment]
You mention it in the blog post, so people may want to understand, what it is?

**Comment by alfonsogarciacaro** [comment]
There's not much more than the description in the docs, what else are you interested to know about?

> Fable has two "hearts" or sides: the .NET side is a daemon (a lightweight TCP server listening by default on port 61225) that waits for messages containing the F# source (.fs) or project (.fsproj) file to parse together with other options, and returns its contents in the form of a Babel compliant AST.
