### ISSUE TITLE
Typescript features documentations ends abruptly with un-styled, uncommented code.

### ISSUE THREAD

**Issue by jonathonchase** [fable-compiler/fable-compiler.github.io#173]
The documentation for TypeScript's features currently ends in the tagged union section with what appears to be a partial implementation of how unions can be implemented in order to resolve to TypeScript interfaces. However, the code for this section seems to cover only the F# portion of declaring the union types and a method that consumes them without the expected generated TypeScript output.

The example here should likely be completed with comments to demonstrate the capability.

**Comment by MangelMaxime** [comment]
Indeed, it seems like I made a note for the interface examples and forgot to complete it before release the new documentation.
