### ISSUE TITLE
Python getting started documentation is not clear

### ISSUE THREAD

**Issue by jkone27** [fable-compiler/fable-compiler.github.io#188]
https://github.com/fable-compiler/fable-compiler.github.io/blob/dev/docs/docs/getting-started/python.md

not very clear, maybe we need to make it shorter but clearer, also not specified that one has to pass the `--lang py` argument to `dotnet fable` command unless checking the cli help

**Comment by MangelMaxime** [comment]
IHMO that example is minimal unless we use templates which I am not in favour of. The reason being in the past maintaining templates made things much harder than keeping the list of commands to run.

I am also mutualising the initial setup for independently of the language to avoid writing the same things each time for each target.

I fixed the command example to add `--lang python` which was something that I forgot to put in it, should be live soon.

If you have suggestion please feel free to share them with us.
