### ISSUE TITLE
FAQ page

### ISSUE THREAD

**Issue by nojaf** [fable-compiler/fable-compiler.github.io#24]
When you are currently stuck with something in Fable and the docs don't cover your problem your goto is the gitter channel.

This is great because generally there is always someone there and the community is wonderful.
However I think it would be nice if we have some sort of FAQ page and instead of answering the same questions in gitter all the time.

The same idea could be helpful for the elmish site as well.

**Comment by alfonsogarciacaro** [comment]
Yes, this is definitely something we need. Unfortunately it's difficult to find past information in a chat like Gitter so people end up asking the same things over and over (not their fault).

We need to make a bit of a cleanup for the web and move the domain as we've lost control over the current one and it's miraculous we can still use it ;) Let's add the FAQ page then. Do you have some suggestions for the first questions we should put there?

**Comment by nojaf** [comment]
Hi, unfortunate you lost fable.io. I don't have any strong suggestions for questions or how to split them up into categories.

I recently explained to someone on gitter that you can use `#if RELEASE` blocks to have code only in the production bundle. Stuff like that would be helpful.

**Comment by alfonsogarciacaro** [comment]
The FAQ has been added, now you've to send questions for it ;) http://fable.io/faq/

**Comment by nojaf** [comment]
Cool, added https://github.com/fable-compiler/Fable/pull/1554 to get things started.
