### ISSUE TITLE
Move to new domain

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/fable-compiler.github.io#27]
I've bought the `fable-compiler.com` domain, we should move everything as we've lost control of the `fable.io` domain and we don't know how long we'll be able to use it. We also need this to use HTTPS.

I nominate @whitetigle as the chief of operations for this as we already had some discussions about it :) We want to have a transition phase where users going to `fable.io` are redirected to the new domain (or at a minimum, a web is displayed showing the new url).

The thing is, I don't know if we can point the `fable.io` domain to another repository at this point. So we may need to keep this repo as is and create a new one for `fable-compiler.com`. Or is there any other solution?

> The main problem of keeping this repo for `fable.io` is we don't get automatic redirections for `fable.io/repl2` and such.

**Comment by ncave** [comment]
There's also `fable.co` available, a bit more expensive per year, but shorter.

**Comment by whitetigle** [comment]
formidable! I'll check that ASAP

**Comment by alfonsogarciacaro** [comment]
It's not super urgent, I guess it can wait until FableConf is over :)

**Comment by alfonsogarciacaro** [comment]
We've recovered control of the `fable.io` domain and HTTPS is enforced now! So we can close this issue :)

**Comment by MangelMaxime** [comment]
Really cool :)

**Comment by whitetigle** [comment]
Incredible! 👏
