### ISSUE TITLE
Focus on landing page

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/fable-compiler.github.io#31]
While revamping the site and moving to a new domain, it may be a good idea to simplify the generation  of the website and its different section, for better maintenance and to make it easier for contributors to focus on different parts. I've already [cleaned up this repo](https://github.com/fable-compiler/fable-compiler.github.io/commit/b7cf1b1a38a2c3b45bd04760c0bb285fbdad451c) but the build process still depend on other repositories to generate the documentation. Maybe it's a good idea to move each section to a different repo and don't worry about having a unified look. An initial proposal could be:

- Keep this repo for the landing page. Then we can focus on have an attractive design with useful information to get started.
- Separate repository for the REPL: already done!
- Move docs to a different repo and use gitbook to build them. This gives us a nice and practical format which developers are already used to and it can make contributions easier.
- Move the blog to Medium? This can also increase Fable visibility among people visiting Medium.

Thoughts? @whitetigle @MangelMaxime

**Comment by whitetigle** [comment]
> Keep this repo for the landing page. Then we can focus on have an attractive design with useful information to get started.

Ok for me.

> Separate repository for the REPL: already done!

👍 

> Move docs to a different repo and use gitbook to build them. This gives us a nice and practical format which developers are already used to and it can make contributions easier.

Yes I too feel it will then get easier to have contributions from users.

> Move the blog to Medium? This can also increase Fable visibility among people visiting Medium.

Absolutely! That's an excellent idea.

**Comment by alfonsogarciacaro** [comment]
I'm going to close this for now, I'm having some other ideas. Maybe for documentation we can use https://docusaurus.io/
