### ISSUE TITLE
Broken link in 'Announcing 2.2'

### ISSUE THREAD

**Issue by selketjah** [fable-compiler/fable-compiler.github.io#38]
> First things first, the summary of changes in fable-compiler 2.2 is as follows (full change list here):

The `here` link (https://github.com/fable-compiler/Fable/blob/635c0379d12ca7348b394310256105e56240408c/src/fable-compiler/RELEASE_NOTES.html) gives me a 404

**Comment by alfonsogarciacaro** [comment]
Ah, damn. That's because the build script changes the `.md` extension to `.html`. I need to fix this, thanks for reporting!
