### ISSUE TITLE
Fable docs: add link to go back to fable.io

### ISSUE THREAD

**Issue by selketjah** [fable-compiler/fable-compiler.github.io#50]
When you go to the documentation, there is no link available to go back to fable.io

**Possible scenario:**
User clicks the link 'docs' to find a specific topic, but does not find it there and wants to go to the blog instead.

Executing this scenario is now not possible

**Comment by MangelMaxime** [comment]
How would you call the link "Home"? 

It's possible in Nacara to add a new element to the navbar

[Source](https://github.com/fable-compiler/fable-compiler.github.io/blob/dev/nacara.json#L10-L34)

**Comment by selketjah** [comment]
For me it would make most sense to press the "Fable" in the top nav

<img width="1366" alt="Screenshot 2019-09-05 at 11 43 50" src="https://user-images.githubusercontent.com/2250570/64331185-a2a03180-cfd2-11e9-8ea0-d0b959ed2076.png">

**Comment by MangelMaxime** [comment]
Hum, that's true I have the [url](https://github.com/fable-compiler/fable-compiler.github.io/blob/dev/nacara.json#L2) field but forget to use it in the template. Will had this to next Nacara version so nothing need to change in this rpeo

**Comment by selketjah** [comment]
Do you want me to create an issue for the Nacara repository?

**Comment by MangelMaxime** [comment]
No that's fine, I am adding it locally already

**Comment by mabasic** [comment]
@alfonsogarciacaro This can now be closed :)

**Comment by alfonsogarciacaro** [comment]
Thanks!
