### ISSUE TITLE
Blog pages are lacking any date information

### ISSUE THREAD

**Issue by pkese** [fable-compiler/fable-compiler.github.io#51]
I'm having an issue that Fable compilation is failing with an error that it can't find `Fable.Helpers.React` 

So I found this page at https://fable.io/blog/Announcing-Fable-React-5.html
but have noticed that there isn't any publication date written anywhere on that page.  
So I don't know how relevant that blog post is (fwiw it might have been years old information).

Please include a publication date on Blog-post pages.

**Comment by alfonsogarciacaro** [comment]
You can see it in the [Blog index](https://fable.io/blog/), but yeah, we should add in the blog page itself :+1:

**Comment by alfonsogarciacaro** [comment]
PRs welcome 😸 

https://github.com/fable-compiler/fable-compiler.github.io/blob/de93c8d4fbfcf81a3a021310661867cb788941e4/src/Main.fs#L79-L88

BTW, the information for the posts including the date [is here](https://github.com/fable-compiler/fable-compiler.github.io/blob/de93c8d4fbfcf81a3a021310661867cb788941e4/src/components/BlogIndex.fs#L53). They would need to be matched with the blog files.

**Comment by pkese** [comment]
I've seen this deployed.
The calendar icon is optically a bit heavy, but since I'm no designer I wouldn't know how to make ti lighter...
Thanks, closing the ticket.
