### ISSUE TITLE
Adapt navbar buttons for mobile display

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/fable-compiler.github.io#6]
![screenshot_2017-09-07-10-00-26](https://user-images.githubusercontent.com/4760796/30152591-d7f1cac2-93b3-11e7-92a9-af8fe4a91779.jpg)

**Comment by mabasic** [comment]
@alfonsogarciacaro @MangelMaxime Can be closed :)

**Comment by alfonsogarciacaro** [comment]
Thanks!
