### ISSUE TITLE
Issue with "start new project" documentation

### ISSUE THREAD

**Issue by inputusernamehere** [fable-compiler/fable-compiler.github.io#95]
Apologies if this is not the correct repo to raise this issue. If it's not, please point me in the right direction.

https://fable.io/docs/2-steps/your-first-fable-project.html

This page tells me to run the command `dotnet new fable-react-elmish`, but I believe it should (now) be `dotnet new fable-elmish-react`, i.e. the order of the words "react" and "elmish" is wrong.

**Comment by alfonsogarciacaro** [comment]
You're definitely right, thanks a lot for reporting! I've noticed the fable-elmish-react is still not updated to Fable 3 though, so I've changed the text to point the user to one of the currently maintained templates: Feliz, Sutil or SAFE.

Thanks a gain and please let us know if you find something else outdated/wrong in the docs!
